### ISSUE TITLE
Please merge latest Beautiful Jekyll updates

### ISSUE THREAD

**Issue by VincentTam** [fahimscirex/fahimscirex.github.io#1]
Hi, this is the owner of the former GitHub bot <span>@</span>staticmanlab that the former verison of Beautiful Jekyll referred to.  I'm writing in response to your "invitation" to my "bot" referred in
https://github.com/fahimscirex/fahimscirex.github.io/blob/be55a1092bbcee6b27932818b1f64110c6450e67/_config.yml#L143
Sorry for any inconvenience and my inaction for one year, but please use your own API instance due to Staticman's maintainer's recommendation in eduardoboucas/staticman<span>#</span>317

> This has been resolved with #319. We are dropping support for the public Staticman instance and are recommending that all users host their own instance. The simplest way to do this is to click the "Deploy to Heroku" button in the README which will allow you to host your own instance for free without the reliability concerns of using a singular public instance. **The public instance will remain running for the time being, though I strongly recommend everyone move away from it.**

As a result, I had stopped the service of my API instance, I removed all references to that through the merged PR daattali/beautiful-jekyll<span>#</span>775 to the blog theme.

**Comment by fahimscirex** [comment]
Yeah, I get it. Thanks for clarifying. I would create a new instance.
